### PR TITLE
Update checksum for k8s.io

### PR DESCRIPTION
**Pull request by dkj**
following go toolchain change ?

### CODE REVIEW

**Comment by sb10** [comment]
Hi, can you specify the steps you took to encounter a problem? I tested develop this afternoon without issue on a fresh machine. Does the problem only happen when using go 1.11.2?

**Comment by dkj** [comment]
The problem did occur with go 1.11.2 . I had a fresh `GOPATH` work directory, separate checkout of `wr`. Note that this "fix" caused a fail with go 1.11.1 in Travis, hence the second commit: all I did was remove the line where a checksum fail was reported - the build process put the new one in there. Far from sure this is a solution!
cf. https://github.com/golang/go/issues/27925

**Comment by sb10** [comment]
Ok, thanks. This or something like it will be applied when moving to 1.11.2 or higher for the release after next.

**Comment by sb10** [comment]
Superseded by #188

**Pull request closed without merging**
