### PR TITLE
Resolve #190: REST API now supports DELETE of jobs to cancel them.

### LINKED ISSUE #190: Job management from REST API
Would it be possible to expose the ability to stop and/or cancel a pending or running job through the REST API? I believe at the moment that functionality is only available through the web interface used by the wr web client.

### PR DESCRIPTION
**Pull request by sb10**
GET status of job also now filterable on State "deletable".

### CODE REVIEW

**Comment by lbarbon** [comment]
Compilation failed on my VM due to the following errors:

```
go: downloading k8s.io/apimachinery v0.0.0-20180228050457-302974c03f7e
verifying github.com/docker/docker@v0.0.0-20180524003928-df5175e1ee95: checksum mismatch
	downloaded: h1:+2d3XdOkkecTDg7o5eQfRT9is97gPs8xTMbZ0iFhf38=
	go.sum:     h1:4sWMxyzSGmCioCJWAzWGZ6HnuBd3uw6DR9cLFJUybgo=
go: downloading k8s.io/apimachinery v0.0.0-20180228050457-302974c03f7e
go: downloading github.com/patrickmn/go-cache v2.1.0+incompatible
verifying k8s.io/client-go@v7.0.0+incompatible: checksum mismatch
	downloaded: h1:gokIETH5yPpln/LuXmg1TLVH5bMSaVQTVxuRizwjWwU=
	go.sum:     h1:kiH+Y6hn+pc78QS/mtBfMJAMIIaWevHi++JvOGEEQp4=
Makefile:18: recipe for target 'install' failed
make: *** [install] Error 1
```

I resolved this by deleting `go.sum` and running `go build` before running `make`.

**Comment by kjsanger** [comment]
I had the same symptom and fix.

**Comment by lbarbon** [comment]
The default value for the `started` and `ended` attributes of the job info returned by `POST` and `DELETE` seems to be -62135596800, not sure if that's to be expected. Personally, I'd be expecting a null value for running jobs and possibly the time of deletion for cancelled jobs as the value for `ended`.

Log from PyWrClient:

```python
In [14]: print([x.__dict__ for x in client.post_jobs([wr.Job('sleep 3600')], parse_body=True)])                                                                                                                 
[{'key': '40d39c777a7ac2f49f5b4790e9fb65b0', 'rep_group': 'manually_added', 'dep_groups': None, 'dependencies': None, 'cmd': 'sleep 3600', 'state': 'ready', 'cwd': '', 'cwd_base': '/tmp', 'home_changed': False, 'behaviours': '', 'mounts': '', 'monitor_docker': '', 'expected_ram': 1000, 'expected_time': 3600, 'requested_disk': 0, 'other_requests': None, 'cores': 0, 'peak_ram': 0, 'peak_disk': 0, 'exited': False, 'exitcode': 0, 'fail_reason': '', 'pid': 0, 'host': '', 'host_id': '', 'host_ip': '', 'walltime': 0, 'cpu_time': 0, 'started': -62135596800, 'ended': -62135596800, 'std_err': '', 'std_out': '', 'env': None, 'attempts': 0, 'similar': 0}]

In [15]: r = client.delete_jobs(wr.JobState.RUNNING)                                                                                                                                                            

In [16]: r.json()                                                                                                                                                                                               
Out[16]: 
[{'Key': '40d39c777a7ac2f49f5b4790e9fb65b0',
  'RepGroup': 'manually_added',
  'LimitGroups': None,
  'DepGroups': None,
  'Dependencies': None,
  'Cmd': 'sleep 3600',
  'State': 'running',
  'Cwd': '',
  'CwdBase': '/tmp',
  'HomeChanged': False,
  'Behaviours': '',
  'Mounts': '',
  'MonitorDocker': '',
  'ExpectedRAM': 100,
  'ExpectedTime': 1800,
  'RequestedDisk': 0,
  'OtherRequests': None,
  'Cores': 0,
  'PeakRAM': 0,
  'PeakDisk': 0,
  'Exited': False,
  'Exitcode': -1,
  'FailReason': '',
  'Pid': 21313,
  'Host': 'u1804a',
  'HostID': '',
  'HostIP': '10.0.2.15',
  'Walltime': 29.56982054,
  'CPUtime': 0,
  'Started': 1554114942,
  'Ended': -62135596800,
  'StdErr': '',
  'StdOut': '',
  'Env': None,
  'Attempts': 1,
  'Similar': 0}]
```

**Comment by sb10** [comment]
The next release will suggest `go clean -modcache` to make things work if you've built wr in the past. But for a fresh install with go 1.11.5+ I was thinking it would work. I'll check a new install myself and update as necessary...

**Comment by lbarbon** [comment]
I successfully tested the deletion of running and buried jobs via the REST API.

Just to check, is it by design that jobs can only be changed from running to buried and from buried to deleted, and not directly from running to deleted?

I observed that if I POST a job with the same command of a job I just deleted (not buried), I get back the same key; is this because the key is actually a hash of the command or because the job is still stored in the wr database (see log below)?

Also, not sure if that would be appropriate or even desirable, but maybe a cascade option to delete a job with its dependencies could prove handy.

```python
In [30]: print([x.__dict__ for x in client.post_jobs([wr.Job('sleep 3600')], parse_body=True)])                          
[{'key': '40d39c777a7ac2f49f5b4790e9fb65b0', 'rep_group': 'manually_added', 'dep_groups': None, 'dependencies': None, 'cmd': 'sleep 3600', 'state': 'ready', 'cwd': '', 'cwd_base': '/tmp', 'home_changed': False, 'behaviours': '', 'mounts': '', 'monitor_docker': '', 'expected_ram': 1000, 'expected_time': 3600, 'requested_disk': 0, 'other_requests': None, 'cores': 0, 'peak_ram': 0, 'peak_disk': 0, 'exited': False, 'exitcode': 0, 'fail_reason': '', 'pid': 0, 'host': '', 'host_id': '', 'host_ip': '', 'walltime': 0, 'cpu_time': 0, 'started': -62135596800, 'ended': -62135596800, 'std_err': '', 'std_out': '', 'env': None, 'attempts': 0, 'similar': 0}]

In [31]: r = client.delete_jobs(wr.JobState.RUNNING)                                                                     

In [32]: r = client.delete_jobs(wr.JobState.DELETABLE)                                                                   

In [33]: print([x.__dict__ for x in client.post_jobs([wr.Job('sleep 3600')], parse_body=True)])                          
[{'key': '40d39c777a7ac2f49f5b4790e9fb65b0', 'rep_group': 'manually_added', 'dep_groups': None, 'dependencies': None, 'cmd': 'sleep 3600', 'state': 'ready', 'cwd': '', 'cwd_base': '/tmp', 'home_changed': False, 'behaviours': '', 'mounts': '', 'monitor_docker': '', 'expected_ram': 1000, 'expected_time': 3600, 'requested_disk': 0, 'other_requests': None, 'cores': 0, 'peak_ram': 0, 'peak_disk': 0, 'exited': False, 'exitcode': 0, 'fail_reason': '', 'pid': 0, 'host': '', 'host_id': '', 'host_ip': '', 'walltime': 0, 'cpu_time': 0, 'started': -62135596800, 'ended': -62135596800, 'std_err': '', 'std_out': '', 'env': None, 'attempts': 0, 'similar': 0}]
```

**Comment by sb10** [comment]
Thanks for testing it and your feedback.

You get the same ID because it's a hash, so that's expected.

I'm not sure its desirable to do an automated cascade to delete dependency trees. Better for the user to know what they're deleting and ask for it explicitly.

Status of jobs using GET has always reported those negative -62135596800 numbers indicating "null" start/end times. I don't want to change that now in case someone relies on this. But please file a bug report if it causes problems and it can be tackled separately.

**Comment by lbarbon** [comment]
I see, thank you for the clarification.

**Pull request merged**
